#!/usr/bin/env python3
"""Generate exact, opt-in pointer patches from an audited local IPA library.

No IPA bytes, paths or personal data are published. Only the five reviewed
legacy layout migrations retain Automatic=on. A cursor fallback is NOT a
claim that the game boots, or a genre-specific gameplay layout.
"""
from __future__ import annotations

import argparse
import copy
import json
import plistlib
import re
from pathlib import Path
from zipfile import ZipFile

from validate_catalog import validate_input_actions

ROOT = Path(__file__).resolve().parents[1]
LIBRARY = ROOT / "controllers/library.json"
RECIPES = ROOT / "controllers/legacy-layouts.json"
REVIEWED = ROOT / "controllers/reviewed-layouts.json"


def reviewed_recipe(game: dict) -> dict | None:
    """Exact-revision proposals stay opt-in, unlike old default migrations."""
    recipes = json.loads(REVIEWED.read_text(encoding="utf-8"))
    recipe = recipes.get(game["executableSha256"])
    if recipe and all(recipe[key] == game[key] for key in ("bundleId", "bundleVersion")):
        return recipe
    return None


def import_inventory(path: Path) -> list[dict]:
    records = []
    for game in json.loads(path.read_text(encoding="utf-8"))["games"]:
        if not game.get("bundle_id") or not game.get("executable_sha256"):
            raise ValueError(f"Missing exact identity: {game.get('file_name')}")
        # The runtime uses CFBundleVersion first, unlike display metadata.
        # Read it from the audited archive rather than guessing from its name.
        with ZipFile(game["path"]) as archive:
            names = [name for name in archive.namelist()
                     if re.fullmatch(r"Payload/[^/]+\.app/Info\.plist", name)]
            if len(names) != 1:
                raise ValueError("Ambiguous main bundle")
            plist = plistlib.loads(archive.read(names[0]))
        version = str(plist.get("CFBundleVersion") or plist.get("CFBundleShortVersionString") or "")
        if not version:
            raise ValueError("Missing bundle version")
        records.append(dict(title=game["title"], bundleId=game["bundle_id"],
                            bundleVersion=version, executableSha256=game["executable_sha256"],
                            archiveStatus=game["status"]))
    identities = {(g["bundleId"], g["bundleVersion"], g["executableSha256"]): g for g in records}
    return sorted(identities.values(), key=lambda g: (g["bundleId"], g["executableSha256"]))


def make_manifest(game: dict, recipes: dict) -> dict:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,199}", game["bundleId"]):
        raise ValueError("Unsafe bundle identity in controller library")
    recipe = recipes.get(game["bundleId"])
    reviewed = reviewed_recipe(game)
    actions = copy.deepcopy(recipe) if recipe else {
        "cursorMode": "relative", "cursorClickButton": "A",
    }
    if reviewed:
        actions = copy.deepcopy(reviewed["input"])
    # Legacy migrations preserve previous behaviour exactly; users can choose
    # mouse-like movement in their profile independently.
    slug = re.sub(r"[^a-z0-9]+", "-", game["bundleId"].lower()).strip("-")[:60]
    patch_id = f"controller-{slug}-{game['executableSha256'][:8]}"
    label = "Геймпад · игровая раскладка" if recipe else "Геймпад · курсор, нажатие и drag"
    return {
        "$schema": "../../schema/sdpatch-v1.schema.json", "formatVersion": 1,
        "id": patch_id, "name": reviewed["name"] if reviewed else f"{label} — {game['title']}"[:128],
        "kind": "input", "status": "experimental", "defaultEnabled": bool(recipe) and not bool(reviewed),
        "priority": 100,
        "target": {"bundleId": game["bundleId"], "bundleVersions": [game["bundleVersion"]],
                   "executableSha256": [game["executableSha256"]]},
        "actions": {"input": actions},
    }


def render(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def outputs(games: list[dict]) -> dict[Path, str]:
    recipes = json.loads(RECIPES.read_text(encoding="utf-8"))
    index = json.loads((ROOT / "index.json").read_text(encoding="utf-8"))
    index["patches"] = [p for p in index["patches"] if not p["id"].startswith("controller-")]
    result = {}
    report = ["# Controller patch coverage", "", "Generated by `build_controller_catalog.py`. Exact executable identities are in `patches/controllers/library.json`.", "",
              "These are control mappings, not new compatibility ratings. Pointer-only patches require manual enabling and are not complete combat/rhythm/multitouch layouts. Legacy layouts retain their previous Automatic behaviour but await a fresh controller/device acceptance run.", "",
              "| Game | Bundle version | Control coverage | Archive check | Patch |", "| --- | --- | --- | --- | --- |"]
    for game in games:
        # Preserve the independently verified GOF1 patch without changing it.
        existing = next((p for p in index["patches"] if not p["id"].startswith("controller-") and p["kind"] == "input"
                         and _matches(ROOT / p["path"], game)), None)
        if existing:
            patch_id, level = existing["id"], "Existing verified mapping (GOF1)"
        else:
            patch = make_manifest(game, recipes)
            patch_id = patch["id"]
            relative = f"catalog/{game['bundleId']}/{patch_id}.sdpatch.json"
            validate_input_actions(ROOT / relative, patch["actions"]["input"])
            result[ROOT / relative] = render(patch)
            index["patches"].append({"id": patch_id, "path": relative,
                                    **{k: patch[k] for k in ("kind", "status", "defaultEnabled")}})
            level = "Legacy game layout (migration)" if game["bundleId"] in recipes else "Pointer only (experimental, off)"
            if reviewed_recipe(game):
                level = "Combat/menu proposal (experimental, off; phone pending)"
        report.append(f"| {game['title']} | {game['bundleVersion']} | {level} | {game['archiveStatus']} | `{patch_id}` |")
    result[ROOT / "index.json"] = render(index)
    result[ROOT.parent / "docs/CONTROLLER_PATCH_COVERAGE.md"] = "\n".join(report) + "\n"
    return result


def _matches(path: Path, game: dict) -> bool:
    target = json.loads(path.read_text(encoding="utf-8"))["target"]
    return (target["bundleId"] == game["bundleId"]
            and game["bundleVersion"] in target.get("bundleVersions", [])
            and game["executableSha256"] in target.get("executableSha256", []))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, action="append", help="Import audited identities; repeat for multiple reports")
    parser.add_argument("--write", action="store_true", help="Write generated catalog; default is check-only")
    args = parser.parse_args()
    games = ([game for path in args.inventory for game in import_inventory(path)]
             if args.inventory else json.loads(LIBRARY.read_text(encoding="utf-8")))
    identities = {(g["bundleId"], g["bundleVersion"], g["executableSha256"]): g for g in games}
    games = sorted(identities.values(), key=lambda g: (g["bundleId"], g["executableSha256"]))
    files = outputs(games)
    files[LIBRARY] = render(games)
    stale = []
    for path, data in files.items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(data, encoding="utf-8")
        elif not path.exists() or path.read_text(encoding="utf-8") != data:
            stale.append(str(path.relative_to(ROOT.parent)))
    if stale:
        print("Stale generated controller catalog: " + ", ".join(stale))
        return 1
    print(f"Controller coverage: {len(games)} exact game revisions; {len(files)} generated files checked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
